(defpackage :com.michieljoris.jc.tokenizer
  (:nicknames :tokenizer)
  (:use cl)
  (:export :load-tokens
	   :get-token
	   :push-mark
	   :pop-mark
	   :discard-mark))

(in-package :tokenizer)

(defparameter *char-fetcher* nil)
(defparameter *token* nil) 
(defparameter *gobbler* nil)
(defparameter *tokens* (list 'empty))
(defparameter *current-token* *tokens*)

(defun get-char () (funcall *char-fetcher*)) 

(defun set-char-fetcher-for (pathname)
  (setf *char-fetcher* 
	(let ((in (open pathname :if-does-not-exist nil))
	      (processing t))
	  (if in
	      (lambda ()
		(if processing 
		    (let (( return-char (read-char in nil)))
		      (cond ((null return-char)
			     (close in)
			     (setf processing nil)))
		      return-char)
		  nil))
	    (lambda () (print "file doesn't exist!!") nil)))))

(defun load-tokens (file-name)
  (set-char-fetcher-for file-name)
  (setf *token* nil)
  (setf *gobbler* #'reset-gobbler)
  (let (char) (setf char "bla")
       (loop while (setf char (get-char)) do (funcall *gobbler* char)))
  (setf *tokens* (cdr *tokens*))
  (setf *current-token* *tokens*))

(defun reset-gobbler (char) (push-char char) (set-gobbler char))
(defun gobble-alpha-chars (char)
  (cond ( (not (or (char= char #\_) (alpha-char-p char)))
	  (set-gobbler char) (pop-token 'alpha_)))
  (push-char char))
(defun gobble-digits (char)
  (cond (( not (digit-char-p char))
	 (set-gobbler char) (pop-token 'number)))
  (push-char char))
(defun gobble-white-space (char)
  (cond ( (not ( white-space-p char))
	  (pop-char)
	  (push-char char)
	  (set-gobbler char))))
(defun gobble-string (char)
  (cond ((char= char #\")
	 (push-char char) (pop-token 'string)
	 (setf *gobbler* #'reset-gobbler))
	(t (push-char char))))
(defun gobble-symbol (char)
  (cond ((or (alphanumericp char) (white-space-p char)
	     (char= char #\_) (char= char #\"))
	 (pop-token 'symbol) (set-gobbler char))
	(t ( cond ((char= char #\/)
		   (setf *gobbler* #'gobble-symbol-or-comment)))))
  (push-char char))
(defun gobble-symbol-or-comment (char)
  (cond ((char= char #\*)
	 (pop-char)
	 (setf *gobbler*
	       (get-gobble-comment-block-function)))
	(t (cond ((char= char #\/)
		  (pop-char)
		  (setf *gobbler* #'gobble-comment-line))
		 (t (gobble-symbol char))))))
(defun gobble-comment-line (char) (if (char= char #\Newline) (setf *gobbler* #'reset-gobbler)))
(defun get-gobble-comment-block-function ()
  (let ((prev-char #\a))
    (lambda (char)
      (if (and (char= char #\/)
	       (equal prev-char #\*))
	  (setf *gobbler* #'reset-gobbler))
      (setf prev-char char))))
(defun set-gobbler (char)
  (setf *gobbler*
	( cond ((alpha-char-p char) #'gobble-alpha-chars)
	       ((digit-char-p char) #'gobble-digits)
	       ((white-space-p char) #'gobble-white-space)
	       ((char= char #\") #'gobble-string)
	       ((char= char #\/) #'gobble-symbol-or-comment)
	       (t #'gobble-symbol-or-comment))))

(defun white-space-p (char) 
   (or (char= char #\Newline) (char= char #\Return) (char= char #\Space)
	      (char= char #\Tab) (char= char #\Linefeed)))

(defun pop-token (type)
  (format t "~a (type ~a)~%" (string (coerce ( reverse *token*) 'string)) type)
  (let ((new-token (list 
		    (cons  (string (coerce ( reverse *token*) 'string))
			   type))))
    (setf (cdr *current-token*) new-token)
    (setf *current-token* new-token))
  (setf *token* nil))

(defun push-char (char) ( setf *token* (cons char *token*)))
(defun pop-char () (setf *token* (cdr *token*)))

(load-tokens "c:/home/EOCS/projects/Pong/Main.jack")
(defun get-token ()
  (let ((return-token (car *current-token*)))
    (setf *current-token* (cdr *current-token*))
    return-token))
(defparameter *mark-stack* (list nil))
(defun push-mark ()
  (push *current-token* *mark-stack*))
(defun pop-mark ()
  (setf *current-token* (pop *mark-stack*)))
(defun discard-mark ()
  (pop *mark-stack*))
